// <auto-generated />
using System;
using BackEnd_ElectronicaDeny.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackEndElectronicaDeny.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250905063917_Datos")]
    partial class Datos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriaNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.DetallePedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallePedido");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Empresa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "electronicadeny@gmail.com",
                            Direccion = "Aldea Chuiquel Central Uno, Sololá, Sololá",
                            Nombre = "Electrónica Deny",
                            Telefono = "3883 6490"
                        });
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.EstadoProductoFisico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EstadoProductoFisico");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Disponible"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Por agotarse / Stock bajo"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Agotado"
                        });
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoPedidoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Productos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Imagen")
                        .HasColumnType("text");

                    b.Property<string>("MarcaProducto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioAdquisicion")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("numeric");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreContacto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefonoContacto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.Estados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Activo"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Inactivo"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Eliminado"
                        });
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RolUsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RolUsuarioId");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Ver Dashboard"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Crear Dashboard"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Editar Dashboard"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Eliminar Dashboard"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Ver Apertura Caja"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Crear Apertura Caja"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Editar Apertura Caja"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Eliminar Apertura Caja"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Ver Cierre Caja"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Crear Cierre Caja"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Editar Cierre Caja"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Eliminar Cierre Caja"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Ver Productos"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Crear Productos"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Editar Productos"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Eliminar Productos"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Ver Categorías"
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "Crear Categorías"
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "Editar Categorías"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Eliminar Categorías"
                        },
                        new
                        {
                            Id = 21,
                            Nombre = "Ver Proveedores"
                        },
                        new
                        {
                            Id = 22,
                            Nombre = "Crear Proveedores"
                        },
                        new
                        {
                            Id = 23,
                            Nombre = "Editar Proveedores"
                        },
                        new
                        {
                            Id = 24,
                            Nombre = "Eliminar Proveedores"
                        },
                        new
                        {
                            Id = 25,
                            Nombre = "Ver Inventario"
                        },
                        new
                        {
                            Id = 26,
                            Nombre = "Crear Inventario"
                        },
                        new
                        {
                            Id = 27,
                            Nombre = "Editar Inventario"
                        },
                        new
                        {
                            Id = 28,
                            Nombre = "Eliminar Inventario"
                        },
                        new
                        {
                            Id = 29,
                            Nombre = "Ver Pedidos"
                        },
                        new
                        {
                            Id = 30,
                            Nombre = "Crear Pedidos"
                        },
                        new
                        {
                            Id = 31,
                            Nombre = "Editar Pedidos"
                        },
                        new
                        {
                            Id = 32,
                            Nombre = "Eliminar Pedidos"
                        },
                        new
                        {
                            Id = 33,
                            Nombre = "Ver Ventas"
                        },
                        new
                        {
                            Id = 34,
                            Nombre = "Crear Ventas"
                        },
                        new
                        {
                            Id = 35,
                            Nombre = "Editar Ventas"
                        },
                        new
                        {
                            Id = 36,
                            Nombre = "Eliminar Ventas"
                        },
                        new
                        {
                            Id = 37,
                            Nombre = "Ver Historial"
                        },
                        new
                        {
                            Id = 38,
                            Nombre = "Crear Historial"
                        },
                        new
                        {
                            Id = 39,
                            Nombre = "Editar Historial"
                        },
                        new
                        {
                            Id = 40,
                            Nombre = "Eliminar Historial"
                        },
                        new
                        {
                            Id = 41,
                            Nombre = "Ver Usuarios"
                        },
                        new
                        {
                            Id = 42,
                            Nombre = "Crear Usuarios"
                        },
                        new
                        {
                            Id = 43,
                            Nombre = "Editar Usuarios"
                        },
                        new
                        {
                            Id = 44,
                            Nombre = "Eliminar Usuarios"
                        },
                        new
                        {
                            Id = 45,
                            Nombre = "Ver Contacto"
                        },
                        new
                        {
                            Id = 46,
                            Nombre = "Crear Contacto"
                        },
                        new
                        {
                            Id = 47,
                            Nombre = "Editar Contacto"
                        },
                        new
                        {
                            Id = 48,
                            Nombre = "Eliminar Contacto"
                        },
                        new
                        {
                            Id = 49,
                            Nombre = "Ver Roles"
                        },
                        new
                        {
                            Id = 50,
                            Nombre = "Crear Roles"
                        },
                        new
                        {
                            Id = 51,
                            Nombre = "Editar Roles"
                        },
                        new
                        {
                            Id = 52,
                            Nombre = "Eliminar Roles"
                        },
                        new
                        {
                            Id = 53,
                            Nombre = "Ver Reportes de Usuarios"
                        },
                        new
                        {
                            Id = 54,
                            Nombre = "Crear Reportes de Usuarios"
                        },
                        new
                        {
                            Id = 55,
                            Nombre = "Editar Reportes de Usuarios"
                        },
                        new
                        {
                            Id = 56,
                            Nombre = "Eliminar Reportes de Usuarios"
                        },
                        new
                        {
                            Id = 57,
                            Nombre = "Ver Reportes de Ventas"
                        },
                        new
                        {
                            Id = 58,
                            Nombre = "Crear Reportes de Ventas"
                        },
                        new
                        {
                            Id = 59,
                            Nombre = "Editar Reportes de Ventas"
                        },
                        new
                        {
                            Id = 60,
                            Nombre = "Eliminar Reportes de Ventas"
                        },
                        new
                        {
                            Id = 61,
                            Nombre = "Ver Reportes de Pedidos"
                        },
                        new
                        {
                            Id = 62,
                            Nombre = "Crear Reportes de Pedidos"
                        },
                        new
                        {
                            Id = 63,
                            Nombre = "Editar Reportes de Pedidos"
                        },
                        new
                        {
                            Id = 64,
                            Nombre = "Eliminar Reportes de Pedidos"
                        },
                        new
                        {
                            Id = 65,
                            Nombre = "Ver Reportes de Inventario"
                        },
                        new
                        {
                            Id = 66,
                            Nombre = "Crear Reportes de Inventario"
                        },
                        new
                        {
                            Id = 67,
                            Nombre = "Editar Reportes de Inventario"
                        },
                        new
                        {
                            Id = 68,
                            Nombre = "Eliminar Reportes de Inventario"
                        });
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.RolPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<int>("PermisoId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("RolPermisos");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            PermisoId = 1,
                            Id = 1
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 2,
                            Id = 2
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 3,
                            Id = 3
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 4,
                            Id = 4
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 5,
                            Id = 5
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 6,
                            Id = 6
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 7,
                            Id = 7
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 8,
                            Id = 8
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 9,
                            Id = 9
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 10,
                            Id = 10
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 11,
                            Id = 11
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 12,
                            Id = 12
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 13,
                            Id = 13
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 14,
                            Id = 14
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 15,
                            Id = 15
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 16,
                            Id = 16
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 17,
                            Id = 17
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 18,
                            Id = 18
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 19,
                            Id = 19
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 20,
                            Id = 20
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 21,
                            Id = 21
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 22,
                            Id = 22
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 23,
                            Id = 23
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 24,
                            Id = 24
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 25,
                            Id = 25
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 26,
                            Id = 26
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 27,
                            Id = 27
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 28,
                            Id = 28
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 29,
                            Id = 29
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 30,
                            Id = 30
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 31,
                            Id = 31
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 32,
                            Id = 32
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 33,
                            Id = 33
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 34,
                            Id = 34
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 35,
                            Id = 35
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 36,
                            Id = 36
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 37,
                            Id = 37
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 38,
                            Id = 38
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 39,
                            Id = 39
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 40,
                            Id = 40
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 41,
                            Id = 41
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 42,
                            Id = 42
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 43,
                            Id = 43
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 44,
                            Id = 44
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 45,
                            Id = 45
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 46,
                            Id = 46
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 47,
                            Id = 47
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 48,
                            Id = 48
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 49,
                            Id = 49
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 50,
                            Id = 50
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 51,
                            Id = 51
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 52,
                            Id = 52
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 53,
                            Id = 53
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 54,
                            Id = 54
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 55,
                            Id = 55
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 56,
                            Id = 56
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 57,
                            Id = 57
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 58,
                            Id = 58
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 59,
                            Id = 59
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 60,
                            Id = 60
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 61,
                            Id = 61
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 62,
                            Id = 62
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 63,
                            Id = 63
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 64,
                            Id = 64
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 65,
                            Id = 65
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 66,
                            Id = 66
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 67,
                            Id = 67
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 68,
                            Id = 68
                        });
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.RolUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Vendedor"
                        });
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoRecuperacion")
                        .HasColumnType("text");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<int?>("EstadoProductoFisicoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaExpiracionCodigo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Imagen")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoInicioSesion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("edad")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("EstadoProductoFisicoId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Xoquic",
                            Contrasena = "@Admin2025",
                            Correo = "electronicadeny@gmail.com",
                            EstadoId = 1,
                            Nombre = "Deny",
                            RolId = 1,
                            Telefono = "5881 6213",
                            edad = 0
                        });
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Categoria", b =>
                {
                    b.HasOne("BackEnd_ElectronicaDeny.Models.Estados", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.DetallePedido", b =>
                {
                    b.HasOne("BackEndElectronicaDeny.Models.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndElectronicaDeny.Models.Productos", "Producto")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Pedido", b =>
                {
                    b.HasOne("BackEndElectronicaDeny.Models.Productos", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndElectronicaDeny.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Productos", b =>
                {
                    b.HasOne("BackEndElectronicaDeny.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEnd_ElectronicaDeny.Models.Estados", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndElectronicaDeny.Models.Proveedor", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Estado");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Proveedor", b =>
                {
                    b.HasOne("BackEnd_ElectronicaDeny.Models.Estados", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.Permiso", b =>
                {
                    b.HasOne("BackEnd_ElectronicaDeny.Models.RolUsuario", null)
                        .WithMany("Permisos")
                        .HasForeignKey("RolUsuarioId");
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.RolPermiso", b =>
                {
                    b.HasOne("BackEnd_ElectronicaDeny.Models.Permiso", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd_ElectronicaDeny.Models.RolUsuario", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.Usuario", b =>
                {
                    b.HasOne("BackEnd_ElectronicaDeny.Models.Estados", "Estado")
                        .WithMany("Usuarios")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEndElectronicaDeny.Models.EstadoProductoFisico", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("EstadoProductoFisicoId");

                    b.HasOne("BackEnd_ElectronicaDeny.Models.RolUsuario", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.EstadoProductoFisico", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Productos", b =>
                {
                    b.Navigation("DetallePedidos");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Proveedor", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.Estados", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.RolUsuario", b =>
                {
                    b.Navigation("Permisos");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
