// <auto-generated />
using System;
using BackEnd_ElectronicaDeny.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackEndElectronicaDeny.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251017034845_MakeRolPermisoIdIdentity")]
    partial class MakeRolPermisoIdIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackEndElectronicaDeny.Models.AperturaCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CajeroNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("FechaAperturaUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<decimal>("MontoApertura")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AperturasCaja", (string)null);
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.CierreCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AperturaCajaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("BaseCaja")
                        .HasColumnType("numeric");

                    b.Property<string>("CajeroNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("FechaCierreUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AperturaCajaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CierresCaja", (string)null);
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.ClasificacionCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("CierreCajaId")
                        .HasColumnType("integer");

                    b.Property<string>("Denominacion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CierreCajaId");

                    b.ToTable("ClasificacionesCaja", (string)null);
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Departamento")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Municipio")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("NIT")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.HasIndex("Telefono")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.DetallePedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductosId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ProductosId");

                    b.ToTable("DetallePedidos");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetalleVenta");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Empresa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "electronicadeny@gmail.com",
                            Direccion = "Aldea Chuiquel Central Uno, Sololá, Sololá",
                            Nombre = "Electrónica Deny",
                            Telefono = "3883 6490"
                        });
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EstadoPedidoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombrePedido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NumeroPedido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPedido")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoPedidoId");

                    b.HasIndex("FechaPedido");

                    b.HasIndex("NumeroPedido")
                        .IsUnique();

                    b.HasIndex("ProveedorId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Productos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Imagen")
                        .HasColumnType("text");

                    b.Property<string>("MarcaProducto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioAdquisicion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreContacto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefonoContacto")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.SaldosCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AperturaCaja")
                        .HasColumnType("numeric");

                    b.Property<int>("CierreCajaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<decimal>("Entradas")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Salidas")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CierreCajaId")
                        .IsUnique();

                    b.ToTable("SaldosCaja", (string)null);
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Stock", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<string>("Imagen")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockDisponible")
                        .HasColumnType("integer");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer");

                    b.HasKey("ProductoId");

                    b.ToTable("Stocks", (string)null);
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cambio")
                        .HasColumnType("numeric");

                    b.Property<string>("ClienteDireccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("ClienteNombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ClienteTelefono")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int?>("ClientesId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoRecibido")
                        .HasColumnType("numeric");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<int>("VendedorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ClientesId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RolUsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RolUsuarioId");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Ver Dashboard"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Crear Dashboard"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Editar Dashboard"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Eliminar Dashboard"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Ver Apertura Caja"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Crear Apertura Caja"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Editar Apertura Caja"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Eliminar Apertura Caja"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Ver Cierre Caja"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Crear Cierre Caja"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Editar Cierre Caja"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Eliminar Cierre Caja"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Ver Productos"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Crear Productos"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Editar Productos"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Eliminar Productos"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Ver Categorías"
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "Crear Categorías"
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "Editar Categorías"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Eliminar Categorías"
                        },
                        new
                        {
                            Id = 21,
                            Nombre = "Ver Proveedores"
                        },
                        new
                        {
                            Id = 22,
                            Nombre = "Crear Proveedores"
                        },
                        new
                        {
                            Id = 23,
                            Nombre = "Editar Proveedores"
                        },
                        new
                        {
                            Id = 24,
                            Nombre = "Eliminar Proveedores"
                        },
                        new
                        {
                            Id = 25,
                            Nombre = "Ver Inventario"
                        },
                        new
                        {
                            Id = 26,
                            Nombre = "Crear Inventario"
                        },
                        new
                        {
                            Id = 27,
                            Nombre = "Editar Inventario"
                        },
                        new
                        {
                            Id = 28,
                            Nombre = "Eliminar Inventario"
                        },
                        new
                        {
                            Id = 29,
                            Nombre = "Ver Pedidos"
                        },
                        new
                        {
                            Id = 30,
                            Nombre = "Crear Pedidos"
                        },
                        new
                        {
                            Id = 31,
                            Nombre = "Editar Pedidos"
                        },
                        new
                        {
                            Id = 32,
                            Nombre = "Eliminar Pedidos"
                        },
                        new
                        {
                            Id = 33,
                            Nombre = "Ver Ventas"
                        },
                        new
                        {
                            Id = 34,
                            Nombre = "Crear Ventas"
                        },
                        new
                        {
                            Id = 35,
                            Nombre = "Editar Ventas"
                        },
                        new
                        {
                            Id = 36,
                            Nombre = "Eliminar Ventas"
                        },
                        new
                        {
                            Id = 37,
                            Nombre = "Ver Historial"
                        },
                        new
                        {
                            Id = 38,
                            Nombre = "Crear Historial"
                        },
                        new
                        {
                            Id = 39,
                            Nombre = "Editar Historial"
                        },
                        new
                        {
                            Id = 40,
                            Nombre = "Eliminar Historial"
                        },
                        new
                        {
                            Id = 41,
                            Nombre = "Ver Usuarios"
                        },
                        new
                        {
                            Id = 42,
                            Nombre = "Crear Usuarios"
                        },
                        new
                        {
                            Id = 43,
                            Nombre = "Editar Usuarios"
                        },
                        new
                        {
                            Id = 44,
                            Nombre = "Eliminar Usuarios"
                        },
                        new
                        {
                            Id = 45,
                            Nombre = "Ver Contacto"
                        },
                        new
                        {
                            Id = 46,
                            Nombre = "Crear Contacto"
                        },
                        new
                        {
                            Id = 47,
                            Nombre = "Editar Contacto"
                        },
                        new
                        {
                            Id = 48,
                            Nombre = "Eliminar Contacto"
                        },
                        new
                        {
                            Id = 49,
                            Nombre = "Ver Roles"
                        },
                        new
                        {
                            Id = 50,
                            Nombre = "Crear Roles"
                        },
                        new
                        {
                            Id = 51,
                            Nombre = "Editar Roles"
                        },
                        new
                        {
                            Id = 52,
                            Nombre = "Eliminar Roles"
                        },
                        new
                        {
                            Id = 53,
                            Nombre = "Ver Reportes de Usuarios"
                        },
                        new
                        {
                            Id = 54,
                            Nombre = "Crear Reportes de Usuarios"
                        },
                        new
                        {
                            Id = 55,
                            Nombre = "Editar Reportes de Usuarios"
                        },
                        new
                        {
                            Id = 56,
                            Nombre = "Eliminar Reportes de Usuarios"
                        },
                        new
                        {
                            Id = 57,
                            Nombre = "Ver Reportes de Ventas"
                        },
                        new
                        {
                            Id = 58,
                            Nombre = "Crear Reportes de Ventas"
                        },
                        new
                        {
                            Id = 59,
                            Nombre = "Editar Reportes de Ventas"
                        },
                        new
                        {
                            Id = 60,
                            Nombre = "Eliminar Reportes de Ventas"
                        },
                        new
                        {
                            Id = 61,
                            Nombre = "Ver Reportes de Pedidos"
                        },
                        new
                        {
                            Id = 62,
                            Nombre = "Crear Reportes de Pedidos"
                        },
                        new
                        {
                            Id = 63,
                            Nombre = "Editar Reportes de Pedidos"
                        },
                        new
                        {
                            Id = 64,
                            Nombre = "Eliminar Reportes de Pedidos"
                        },
                        new
                        {
                            Id = 65,
                            Nombre = "Ver Reportes de Inventario"
                        },
                        new
                        {
                            Id = 66,
                            Nombre = "Crear Reportes de Inventario"
                        },
                        new
                        {
                            Id = 67,
                            Nombre = "Editar Reportes de Inventario"
                        },
                        new
                        {
                            Id = 68,
                            Nombre = "Eliminar Reportes de Inventario"
                        });
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.RolPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PermisoId")
                        .HasColumnType("integer");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PermisoId");

                    b.HasIndex("RolId", "PermisoId")
                        .IsUnique();

                    b.ToTable("RolPermisos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermisoId = 1,
                            RolId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermisoId = 2,
                            RolId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermisoId = 3,
                            RolId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermisoId = 4,
                            RolId = 1
                        },
                        new
                        {
                            Id = 5,
                            PermisoId = 5,
                            RolId = 1
                        },
                        new
                        {
                            Id = 6,
                            PermisoId = 6,
                            RolId = 1
                        },
                        new
                        {
                            Id = 7,
                            PermisoId = 7,
                            RolId = 1
                        },
                        new
                        {
                            Id = 8,
                            PermisoId = 8,
                            RolId = 1
                        },
                        new
                        {
                            Id = 9,
                            PermisoId = 9,
                            RolId = 1
                        },
                        new
                        {
                            Id = 10,
                            PermisoId = 10,
                            RolId = 1
                        },
                        new
                        {
                            Id = 11,
                            PermisoId = 11,
                            RolId = 1
                        },
                        new
                        {
                            Id = 12,
                            PermisoId = 12,
                            RolId = 1
                        },
                        new
                        {
                            Id = 13,
                            PermisoId = 13,
                            RolId = 1
                        },
                        new
                        {
                            Id = 14,
                            PermisoId = 14,
                            RolId = 1
                        },
                        new
                        {
                            Id = 15,
                            PermisoId = 15,
                            RolId = 1
                        },
                        new
                        {
                            Id = 16,
                            PermisoId = 16,
                            RolId = 1
                        },
                        new
                        {
                            Id = 17,
                            PermisoId = 17,
                            RolId = 1
                        },
                        new
                        {
                            Id = 18,
                            PermisoId = 18,
                            RolId = 1
                        },
                        new
                        {
                            Id = 19,
                            PermisoId = 19,
                            RolId = 1
                        },
                        new
                        {
                            Id = 20,
                            PermisoId = 20,
                            RolId = 1
                        },
                        new
                        {
                            Id = 21,
                            PermisoId = 21,
                            RolId = 1
                        },
                        new
                        {
                            Id = 22,
                            PermisoId = 22,
                            RolId = 1
                        },
                        new
                        {
                            Id = 23,
                            PermisoId = 23,
                            RolId = 1
                        },
                        new
                        {
                            Id = 24,
                            PermisoId = 24,
                            RolId = 1
                        },
                        new
                        {
                            Id = 25,
                            PermisoId = 25,
                            RolId = 1
                        },
                        new
                        {
                            Id = 26,
                            PermisoId = 26,
                            RolId = 1
                        },
                        new
                        {
                            Id = 27,
                            PermisoId = 27,
                            RolId = 1
                        },
                        new
                        {
                            Id = 28,
                            PermisoId = 28,
                            RolId = 1
                        },
                        new
                        {
                            Id = 29,
                            PermisoId = 29,
                            RolId = 1
                        },
                        new
                        {
                            Id = 30,
                            PermisoId = 30,
                            RolId = 1
                        },
                        new
                        {
                            Id = 31,
                            PermisoId = 31,
                            RolId = 1
                        },
                        new
                        {
                            Id = 32,
                            PermisoId = 32,
                            RolId = 1
                        },
                        new
                        {
                            Id = 33,
                            PermisoId = 33,
                            RolId = 1
                        },
                        new
                        {
                            Id = 34,
                            PermisoId = 34,
                            RolId = 1
                        },
                        new
                        {
                            Id = 35,
                            PermisoId = 35,
                            RolId = 1
                        },
                        new
                        {
                            Id = 36,
                            PermisoId = 36,
                            RolId = 1
                        },
                        new
                        {
                            Id = 37,
                            PermisoId = 37,
                            RolId = 1
                        },
                        new
                        {
                            Id = 38,
                            PermisoId = 38,
                            RolId = 1
                        },
                        new
                        {
                            Id = 39,
                            PermisoId = 39,
                            RolId = 1
                        },
                        new
                        {
                            Id = 40,
                            PermisoId = 40,
                            RolId = 1
                        },
                        new
                        {
                            Id = 41,
                            PermisoId = 41,
                            RolId = 1
                        },
                        new
                        {
                            Id = 42,
                            PermisoId = 42,
                            RolId = 1
                        },
                        new
                        {
                            Id = 43,
                            PermisoId = 43,
                            RolId = 1
                        },
                        new
                        {
                            Id = 44,
                            PermisoId = 44,
                            RolId = 1
                        },
                        new
                        {
                            Id = 45,
                            PermisoId = 45,
                            RolId = 1
                        },
                        new
                        {
                            Id = 46,
                            PermisoId = 46,
                            RolId = 1
                        },
                        new
                        {
                            Id = 47,
                            PermisoId = 47,
                            RolId = 1
                        },
                        new
                        {
                            Id = 48,
                            PermisoId = 48,
                            RolId = 1
                        },
                        new
                        {
                            Id = 49,
                            PermisoId = 49,
                            RolId = 1
                        },
                        new
                        {
                            Id = 50,
                            PermisoId = 50,
                            RolId = 1
                        },
                        new
                        {
                            Id = 51,
                            PermisoId = 51,
                            RolId = 1
                        },
                        new
                        {
                            Id = 52,
                            PermisoId = 52,
                            RolId = 1
                        },
                        new
                        {
                            Id = 53,
                            PermisoId = 53,
                            RolId = 1
                        },
                        new
                        {
                            Id = 54,
                            PermisoId = 54,
                            RolId = 1
                        },
                        new
                        {
                            Id = 55,
                            PermisoId = 55,
                            RolId = 1
                        },
                        new
                        {
                            Id = 56,
                            PermisoId = 56,
                            RolId = 1
                        },
                        new
                        {
                            Id = 57,
                            PermisoId = 57,
                            RolId = 1
                        },
                        new
                        {
                            Id = 58,
                            PermisoId = 58,
                            RolId = 1
                        },
                        new
                        {
                            Id = 59,
                            PermisoId = 59,
                            RolId = 1
                        },
                        new
                        {
                            Id = 60,
                            PermisoId = 60,
                            RolId = 1
                        },
                        new
                        {
                            Id = 61,
                            PermisoId = 61,
                            RolId = 1
                        },
                        new
                        {
                            Id = 62,
                            PermisoId = 62,
                            RolId = 1
                        },
                        new
                        {
                            Id = 63,
                            PermisoId = 63,
                            RolId = 1
                        },
                        new
                        {
                            Id = 64,
                            PermisoId = 64,
                            RolId = 1
                        },
                        new
                        {
                            Id = 65,
                            PermisoId = 65,
                            RolId = 1
                        },
                        new
                        {
                            Id = 66,
                            PermisoId = 66,
                            RolId = 1
                        },
                        new
                        {
                            Id = 67,
                            PermisoId = 67,
                            RolId = 1
                        },
                        new
                        {
                            Id = 68,
                            PermisoId = 68,
                            RolId = 1
                        });
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.RolUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Vendedor"
                        });
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoRecuperacion")
                        .HasColumnType("text");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaExpiracionCodigo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Imagen")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime?>("UltimoInicioSesion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("edad")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Xoquic",
                            Contrasena = "@Admin2025",
                            Correo = "electronicadeny@gmail.com",
                            Estado = 1,
                            Nombre = "Deny",
                            RolId = 1,
                            Telefono = "5881 6213",
                            edad = 0
                        });
                });

            modelBuilder.Entity("Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriaNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.AperturaCaja", b =>
                {
                    b.HasOne("BackEnd_ElectronicaDeny.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.CierreCaja", b =>
                {
                    b.HasOne("BackEndElectronicaDeny.Models.AperturaCaja", "AperturaCaja")
                        .WithMany()
                        .HasForeignKey("AperturaCajaId");

                    b.HasOne("BackEnd_ElectronicaDeny.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AperturaCaja");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.ClasificacionCaja", b =>
                {
                    b.HasOne("BackEndElectronicaDeny.Models.CierreCaja", "CierreCaja")
                        .WithMany("Clasificaciones")
                        .HasForeignKey("CierreCajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CierreCaja");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.DetallePedido", b =>
                {
                    b.HasOne("BackEndElectronicaDeny.Models.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndElectronicaDeny.Models.Productos", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEndElectronicaDeny.Models.Productos", null)
                        .WithMany("DetallePedidos")
                        .HasForeignKey("ProductosId");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.DetalleVenta", b =>
                {
                    b.HasOne("BackEndElectronicaDeny.Models.Productos", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndElectronicaDeny.Models.Venta", "Venta")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Pedido", b =>
                {
                    b.HasOne("BackEndElectronicaDeny.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Productos", b =>
                {
                    b.HasOne("Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEndElectronicaDeny.Models.Proveedor", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.SaldosCaja", b =>
                {
                    b.HasOne("BackEndElectronicaDeny.Models.CierreCaja", "CierreCaja")
                        .WithOne("Saldos")
                        .HasForeignKey("BackEndElectronicaDeny.Models.SaldosCaja", "CierreCajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CierreCaja");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Stock", b =>
                {
                    b.HasOne("BackEndElectronicaDeny.Models.Productos", "Producto")
                        .WithOne("Stock")
                        .HasForeignKey("BackEndElectronicaDeny.Models.Stock", "ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Venta", b =>
                {
                    b.HasOne("BackEndElectronicaDeny.Models.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BackEndElectronicaDeny.Models.Clientes", null)
                        .WithMany("Ventas")
                        .HasForeignKey("ClientesId");

                    b.HasOne("BackEnd_ElectronicaDeny.Models.Usuario", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.Permiso", b =>
                {
                    b.HasOne("BackEnd_ElectronicaDeny.Models.RolUsuario", null)
                        .WithMany("Permisos")
                        .HasForeignKey("RolUsuarioId");
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.RolPermiso", b =>
                {
                    b.HasOne("BackEnd_ElectronicaDeny.Models.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd_ElectronicaDeny.Models.RolUsuario", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.Usuario", b =>
                {
                    b.HasOne("BackEnd_ElectronicaDeny.Models.RolUsuario", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.CierreCaja", b =>
                {
                    b.Navigation("Clasificaciones");

                    b.Navigation("Saldos")
                        .IsRequired();
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Clientes", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Productos", b =>
                {
                    b.Navigation("DetallePedidos");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Proveedor", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("BackEndElectronicaDeny.Models.Venta", b =>
                {
                    b.Navigation("DetallesVenta");
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.RolUsuario", b =>
                {
                    b.Navigation("Permisos");

                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Categoria", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
