// <auto-generated />
using System;
using BackEnd_ElectronicaDeny.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackEnd_ElectronicaDeny.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.EstadoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Activo"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Inactivo"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Eliminado"
                        });
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RolUsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RolUsuarioId");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Ver Dashboard"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Crear Dashboard"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Editar Dashboard"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Eliminar Dashboard"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Ver Apertura Caja"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Crear Apertura Caja"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Editar Apertura Caja"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Eliminar Apertura Caja"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Ver Cierre Caja"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Crear Cierre Caja"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Editar Cierre Caja"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Eliminar Cierre Caja"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Ver Productos"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Crear Productos"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Editar Productos"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Eliminar Productos"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Ver Categorías"
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "Crear Categorías"
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "Editar Categorías"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Eliminar Categorías"
                        },
                        new
                        {
                            Id = 21,
                            Nombre = "Ver Proveedores"
                        },
                        new
                        {
                            Id = 22,
                            Nombre = "Crear Proveedores"
                        },
                        new
                        {
                            Id = 23,
                            Nombre = "Editar Proveedores"
                        },
                        new
                        {
                            Id = 24,
                            Nombre = "Eliminar Proveedores"
                        },
                        new
                        {
                            Id = 25,
                            Nombre = "Ver Inventario"
                        },
                        new
                        {
                            Id = 26,
                            Nombre = "Crear Inventario"
                        },
                        new
                        {
                            Id = 27,
                            Nombre = "Editar Inventario"
                        },
                        new
                        {
                            Id = 28,
                            Nombre = "Eliminar Inventario"
                        },
                        new
                        {
                            Id = 29,
                            Nombre = "Ver Pedidos"
                        },
                        new
                        {
                            Id = 30,
                            Nombre = "Crear Pedidos"
                        },
                        new
                        {
                            Id = 31,
                            Nombre = "Editar Pedidos"
                        },
                        new
                        {
                            Id = 32,
                            Nombre = "Eliminar Pedidos"
                        },
                        new
                        {
                            Id = 33,
                            Nombre = "Ver Ventas"
                        },
                        new
                        {
                            Id = 34,
                            Nombre = "Crear Ventas"
                        },
                        new
                        {
                            Id = 35,
                            Nombre = "Editar Ventas"
                        },
                        new
                        {
                            Id = 36,
                            Nombre = "Eliminar Ventas"
                        },
                        new
                        {
                            Id = 37,
                            Nombre = "Ver Historial"
                        },
                        new
                        {
                            Id = 38,
                            Nombre = "Crear Historial"
                        },
                        new
                        {
                            Id = 39,
                            Nombre = "Editar Historial"
                        },
                        new
                        {
                            Id = 40,
                            Nombre = "Eliminar Historial"
                        },
                        new
                        {
                            Id = 41,
                            Nombre = "Ver Usuarios"
                        },
                        new
                        {
                            Id = 42,
                            Nombre = "Crear Usuarios"
                        },
                        new
                        {
                            Id = 43,
                            Nombre = "Editar Usuarios"
                        },
                        new
                        {
                            Id = 44,
                            Nombre = "Eliminar Usuarios"
                        },
                        new
                        {
                            Id = 45,
                            Nombre = "Ver Contacto"
                        },
                        new
                        {
                            Id = 46,
                            Nombre = "Crear Contacto"
                        },
                        new
                        {
                            Id = 47,
                            Nombre = "Editar Contacto"
                        },
                        new
                        {
                            Id = 48,
                            Nombre = "Eliminar Contacto"
                        },
                        new
                        {
                            Id = 49,
                            Nombre = "Ver Roles"
                        },
                        new
                        {
                            Id = 50,
                            Nombre = "Crear Roles"
                        },
                        new
                        {
                            Id = 51,
                            Nombre = "Editar Roles"
                        },
                        new
                        {
                            Id = 52,
                            Nombre = "Eliminar Roles"
                        },
                        new
                        {
                            Id = 53,
                            Nombre = "Ver Reportes de Usuarios"
                        },
                        new
                        {
                            Id = 54,
                            Nombre = "Crear Reportes de Usuarios"
                        },
                        new
                        {
                            Id = 55,
                            Nombre = "Editar Reportes de Usuarios"
                        },
                        new
                        {
                            Id = 56,
                            Nombre = "Eliminar Reportes de Usuarios"
                        });
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.RolUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Vendedor"
                        });
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoRecuperacion")
                        .HasColumnType("text");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaExpiracionCodigo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Imagen")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoInicioSesion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Chumil",
                            Contrasena = "@Admin2025",
                            Correo = "tiendakeytelin@gmail.com",
                            EstadoId = 1,
                            Nombre = "Edwin",
                            RolId = 1,
                            Telefono = "5881 6213"
                        });
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.Permiso", b =>
                {
                    b.HasOne("BackEnd_ElectronicaDeny.Models.RolUsuario", null)
                        .WithMany("Permisos")
                        .HasForeignKey("RolUsuarioId");
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.Usuario", b =>
                {
                    b.HasOne("BackEnd_ElectronicaDeny.Models.EstadoUsuario", "Estado")
                        .WithMany("Usuarios")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEnd_ElectronicaDeny.Models.RolUsuario", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.EstadoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BackEnd_ElectronicaDeny.Models.RolUsuario", b =>
                {
                    b.Navigation("Permisos");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
